### PR TITLE
Fix tripal image version

### PR DESCRIPTION
**Pull request by loraine-gueguen**
Fix https://github.com/abretaud/docker-tripal-demo/issues/2

### CODE REVIEW

**Comment by abretaud** [comment]
I *think* @mboudet is working (or planning to?) on this update, what do you think @mboudet?

**Comment by mboudet** [comment]
I am, but since the master branch is still on tripal V2 for now, it's fine to merge this one.
I will make a separate branch for v3 when it's ready.

**Comment by abretaud** [comment]
> I am, but since the master branch is still on tripal V2 for now, it's fine to merge this one.

hum, which master branch? the tripal docker image is now v3 by default

**Comment by abretaud** [comment]
Nevermind, I understand now...

**Pull request merged**
